name: backend for ci/cd

# 트리거
on:
  # 원인 : 푸시
  push:
    # 대상 브런치
    branches:
      # 대상 브런치는 main
      - master

# 해야될 일 => jobs
jobs:
  # 잡 전체에 대한 이름 (커스텀)
  cicd-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository내 파일들 checkout(불러오기) 수행
        uses: actions/checkout@v4

      # JDK 17 버전 설치
      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      # Application.yml 동적 생성
      - name: 단위 테스트 및 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: 관리상 빌드된 결과물의 이름을 변경 처리
        run:  |
          mv ./build/libs/*SNAPSHOT.jar ./run.jar
          ls 

      # EC2로 업로드
      - name: EC2에 jar파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: run.jar
          target: /home/ubuntu/server/demo

      # EC2 접속 서버 가동!!
      # https://github.com/appleboy/ssh-action
      - name : SSH로 EC2에 접속후 서버가동
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/server/web
            mkdir /home/ubuntu/server/web
            mv /home/ubuntu/server/demo/run.jar /home/ubuntu/server/web/run.jar
            cd /home/ubuntu/server/web
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar run.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/server/demo